osbf3 whitelist add from 'Scott Schwartz <schwartz@groucho.cse.psu.edu>'
osbf3 whitelist add from 'Neil Weisenfeld <weisen@alw.nih.gov>'
osbf3 whitelist add from 'Vijay Gill <vijay@gl.umbc.edu>'
osbf3 whitelist add from 'Chris Siebenmann <cks@hawkwind.utcs.toronto.edu>'
osbf3 whitelist add from 'Jerry W Johnson <jwjohn@ecst.csuchico.edu>'
osbf3 whitelist add from 'Vijay Gill <vijay@umbc.edu>'
osbf3 whitelist add from '"Linda Lilburne" <LilburneL@landcare.cri.nz>'
osbf3 whitelist add from '"Ted Zobeck" <tzobeck@lubbock.ars.ag.gov>'
osbf3 whitelist add from 'Will Mengarini <mengarini@delphi.com>'
osbf3 whitelist add from 'Zvi Lamm <mslamm@pluto.mscc.huji.ac.il>'
osbf3 whitelist add from 'Steve Kotsopoulos <steve@ecf.toronto.edu>'
osbf3 whitelist add from '"j.c.lin" <jclin@ccms.ntu.edu.tw>'
osbf3 whitelist add from '"Nigel Roles" <ngr@symbionics.co.uk>'
osbf3 whitelist add from 'Heiko Wengler <hw@plato.Chemietechnik.Uni-Dortmund.DE>'
osbf3 whitelist add from 'Shannon Bradford <sbradfor@ecst.csuchico.edu>'
osbf3 whitelist add from 'John and Nellena Difilippo <difilipp@whidbey.net>'
osbf3 whitelist add from 'Scott Schwartz <schwartz@galapagos.cse.psu.edu>'
osbf3 whitelist add from 'Alejandro Garza Gonzalez <agarza@ci.mty.itesm.mx>'
osbf3 whitelist add from 'ICSC Canada <icsc@compusmart.ab.ca>'
osbf3 whitelist add from 'Robert Desimone <Robert.De_Simone@sophia.inria.fr>'
osbf3 whitelist add from '"Rosemary Arnoux" <r.arnoux@auckland.ac.nz>'
osbf3 whitelist add from '"Adam H. Kerman" <ahk@chinet.chinet.com>'
osbf3 whitelist add from 'Brian Schmalz <Brian.Schmalz@corp.honeywell.com>'
osbf3 whitelist add from 'Edward M Greshko <Edward.M.Greshko@cdc.com>'
osbf3 whitelist add from 'Andrew Vardy <avardy@morgan.ucs.mun.ca>'
osbf3 whitelist add from 'Fabio Coatti <cova@felix.unife.it>'
osbf3 whitelist add from '"Everett, Marty" <MEverett@IKON.com>'
osbf3 whitelist add from 'Drachen <drachen@eni.net>'
osbf3 whitelist add from '"Robin S. Socha" <robin@franck.pc.uni-koeln.de>'
osbf3 whitelist add from 'Norbert Koch <norbert.koch@delta-ii.de>'
osbf3 whitelist add from 'Jennifer  Call <call@Pharmacy.Arizona.EDU>'
osbf3 whitelist add from '"Colin J. Raven" <cjraven@quik.com>'
osbf3 whitelist add from '"K.M. Jeary" <kmj1000@ucs.cam.ac.uk>'
osbf3 whitelist add from '"Cesar Benitez" <sexr@hotmail.com>'
osbf3 whitelist add from '"Max E. Coates" <mcoates@sk.sympatico.ca>'
osbf3 whitelist add from 'John Heenan <johnhe@syd.net.au>'
osbf3 whitelist add from 'Sapan Goel <sapan@ganga.mnrec.ernet.in>'
osbf3 whitelist add from 'ruben <rufranco@utep.edu>'
osbf3 whitelist add from 'SAROJA SREENIVASAN <sarojas@md2.vsnl.net.in>'
osbf3 whitelist add from 'SandraB <sandra@happy.com>'
osbf3 whitelist add from 'Y M Kung   Charles <koebi@alumni.ust.hk>'
osbf3 whitelist add from 'Robert Harman <rharman@ece.wvu.edu>'
osbf3 whitelist add from 'Alan Kiplinger <akipling@sec.noaa.gov>'
osbf3 whitelist add from 'Didier Godefroy <godefro@ibm.net>'
osbf3 whitelist add from 'Alicia Goodman <aliciag@BGNet.bgsu.edu>'
osbf3 whitelist add from 'Shoeless in San Jose <batchman@slip.net>'
osbf3 whitelist add from 'The Traveller <kosman@cisunix.unh.edu>'
osbf3 whitelist add from '"Brennan Mair" <gysmo@es.co.nz>'
osbf3 whitelist add from '"Michael S. Reiling" <macman@inreach.com>'
osbf3 whitelist add from 'Richard Drushel <drushel@apk.net>'
osbf3 whitelist add from 'Stacker <j-stark@uiuc.edu>'
osbf3 whitelist add from '"German Madinabeitia" <german@siapi.es>'
osbf3 whitelist add from 'Randy Sargent <rsargent@newtonlabs.com>'
osbf3 whitelist add from '"Sonam Chauhan (CS)" <chauhan@babbage.csee.usf.edu>'
osbf3 whitelist add from 'root <root@snotnose.wizard.org>'
osbf3 whitelist add from '"owen popplestone" <owenp@islandnet.com>'
osbf3 whitelist add from 'David Kott <dakott@alpha.delta.edu>'
osbf3 whitelist add from 'Richard <rshirk@sfgate.com>'
osbf3 whitelist add from '"Frangois" <moonfish@club-internet.fr>'
osbf3 whitelist add from 'Will Bain <willbain@cs.umt.edu>'
osbf3 whitelist add from 'JAN BOS EP <JANBOSEP@aol.com>'
osbf3 whitelist add from 'Mike Downey <mdowney@optimizeinc.com>'
osbf3 whitelist add from '"Darth Vader" <rent-a-nerd@technologist.com>'
osbf3 whitelist add from 'Jan Sipke van der Veen <j.s.vanderveen@student.utwente.nl>'
osbf3 whitelist add from '"Scott Mitchell Simon" <sms7@arl.wustl.edu>'
osbf3 whitelist add from '"E. Baeck" <erwin.baeck@styria.com>'
osbf3 whitelist add from 'Wong Sy Ming <smwong@post1.com>'
osbf3 whitelist add from '"Bruce A. Moore" <bamoore@bloomington.in.us>'
osbf3 whitelist add from '"Duncan Orthner" <orthner@[192.168.0.1]>'
osbf3 whitelist add from '"Charles Hacker EAS" <C.Hacker@ste.gu.edu.au>'
osbf3 whitelist add from '"Jonathan K. Church" <churchie@nwu.edu>'
osbf3 whitelist add from 'Bernd Klein <Bernd.Klein@pdv-online.de>'
osbf3 whitelist add from 'MAR ERICSON <mar@cooper.edu>'
osbf3 whitelist add from '"Patrick E. Hacker" <patrick.e.hacker@tek.COM>'
osbf3 whitelist add from 'John Wong <u2174730@ee.unsw.edu.au>'
osbf3 whitelist add from '"Paul E. Rybski" <rybski@cs.umn.edu>'
osbf3 whitelist add from 'BMajik5127 <BMajik5127@aol.com>'
osbf3 whitelist add from '"Pandit Panburana" <pdp@ix.netcom.com>'
osbf3 whitelist add from 'John Sarkany <sarkany@idirect.com>'
osbf3 whitelist add from '"Jeff Loeliger" <r12110@email.sps.mot.com>'
osbf3 whitelist add from '"Bernd.Klein" <Bernd.Klein@pdv-online.de>'
osbf3 whitelist add from '"Fred G. Martin" <fredm@media.mit.edu>'
osbf3 whitelist add from '"Mike Davis" <ipscone@halcyon.com>'
osbf3 whitelist add from 'Brett Anthony <anthonyb@ecs.csus.edu>'
osbf3 whitelist add from 'Kenji Arisawa <arisawa@ken.aichi-u.ac.jp>'
osbf3 whitelist add from '"Curt Mills, WE7U" <hacker@tc.fluke.com>'
osbf3 whitelist add from '"Sterling" <sterlingc@erols.com>'
osbf3 whitelist add from 'Mike Vande Weghe <vandeweg@nameconnector.com>'
osbf3 whitelist add from 'Geir Atle Storhaug <Geir-Atle.Storhaug@ffi.no>'
osbf3 whitelist add from '"Luc Bodson" <cyberoptics@pandora.be>'
osbf3 whitelist add from 'Tim Gold <goldt@et.byu.edu>'
osbf3 whitelist add from 'Jim Fong <jfong@hooked.net>'
osbf3 whitelist add from 'John Hatton <JohnHa@icsplc.co.uk>'
osbf3 whitelist add from 'Chad K Humberstone <humbersc@et.byu.edu>'
osbf3 whitelist add from '"phillip chia" <philchia@singnet.com.sg>'
osbf3 whitelist add from 'Sheridan Edward Ethier <seethier@zeus.UWaterloo.ca>'
osbf3 whitelist add from 'Rick Moll <rickmoll@mvp.net>'
osbf3 whitelist add from 'Skye Legon <slegon@watfast.uwaterloo.ca>'
osbf3 whitelist add from 'Alf Kuchenbuch <alfk@eikon.tum.de>'
osbf3 whitelist add from 'Chuck McManis <cmcmanis@freegate.com>'
osbf3 whitelist add from 'Mario Garcia <mariogar@calpoly.edu>'
osbf3 whitelist add from 'Richard meester <richard.meester@chess.nl>'
osbf3 whitelist add from 'Zach Johnson <zachjo@ibm.net>'
osbf3 whitelist add from 'Marcelo Manjon <manjon@labone.net>'
osbf3 whitelist add from 'Will <willbain@cs.umt.edu>'
osbf3 whitelist add from 'Remi Desrosiers <harlock@videotron.ca>'
osbf3 whitelist add from 'The Plumber <jhoffman@it.sait.ab.ca>'
osbf3 whitelist add from 'Andre Philippi <philippi@earthlink.net>'
osbf3 whitelist add from 'Jay Hauser <hauser@physics.ucla.edu>'
osbf3 whitelist add from '"Adam Oliver" <oli@wantree.com.au>'
osbf3 whitelist add from 'Michael WIll de Laforcade <mwill@dris.com>'
osbf3 whitelist add from '"Scott R. Harris" <srharris@phoenix.Princeton.EDU>'
osbf3 whitelist add from '"MADHU SUDAN GADDAMIDI" <madhug1@hotmail.com>'
osbf3 whitelist add from 'HECTOR NORIEGA <110060.2126@compuserve.com>'
osbf3 whitelist add from 'Francois <zcees34@ucl.ac.uk>'
osbf3 whitelist add from '"Terry P. Gathright" <669@worldnet.att.net>'
osbf3 whitelist add from 'Michael Carmody <sanfranmike@worldnet.att.net>'
osbf3 whitelist add from '"G. David Butler" <gdb@dbSystems.com>'
osbf3 whitelist add from '"Dave Hensley" <dhensley@cyberramp.net>'
osbf3 whitelist add from 'Digby Tarvin <digbyt@acm.org>'
osbf3 whitelist add from 'brett anthony <anthonyb@ecs.csus.edu>'
osbf3 whitelist add from 'Scott Schwartz <schwartz@bio.cse.psu.edu>'
osbf3 whitelist add from 'Christopher Prosser <christopherprosser@yahoo.com>'
osbf3 whitelist add from '"ED Spike, E&CE Dept." <spike@engmail.uwaterloo.ca>'
osbf3 whitelist add from 'Mike Downey <downeym@bellsouth.net>'
osbf3 whitelist add from '"Tey Chee Beng" <cbtey@singnet.com.sg>'
osbf3 whitelist add from 'Justin Daniel Gullotta <gulloj@rpi.edu>'
osbf3 whitelist add from 'Chris Johnson <chrisj@mindless.com>'
osbf3 whitelist add from '"Aaron Edsinger" <aarone@sirius.com>'
osbf3 whitelist add from 'J.D.Gullotta.. <gulloj@rpi.edu>'
osbf3 whitelist add from '"FEDERICO SANTELLO" <fedsante@tin.it>'
osbf3 whitelist add from '"Gansler Mike (K1-Fh/ESC1)" <Mike.Gansler@Bosch-Brakes.com>'
osbf3 whitelist add from 'Jonathan Swaby <jonathan.swaby@vpss.gatech.edu>'
osbf3 whitelist add from '"Leenman, Eric (Eric)" <eleenman@lucent.com>'
osbf3 whitelist add from '"Bill Denzel" <wdenzel@polymail.cpunix.calpoly.edu>'
osbf3 whitelist add from 'Michael Toh <leahcim@pacific.net.sg>'
osbf3 whitelist add from 'Jeremy Foo <soundstruck@pacific.net.sg>'
osbf3 whitelist add from '"Rien Matthijsse" <marobi@direct.A2000.nl>'
osbf3 whitelist add from '"Mike Jones"<michaelj@wt.net>'
osbf3 whitelist add from '"mark williamson" <markw@tabnet.com>'
osbf3 whitelist add from '"Wayne Rademacher" <ridgetec@net-info.com>'
osbf3 whitelist add from '"Lewis Patterson" <lewis@bsc.edu>'
osbf3 whitelist add from '"Graham, J. Todd" <grahamjt@Maritz.com>'
osbf3 whitelist add from 'Alf Kuchenbuch <alf.kuchenbuch@usa.net>'
osbf3 whitelist add from '"SHETTI.NITIN.MANGESH" <shettin@giasbmc.vsnl.net.in>'
osbf3 whitelist add from 'Ranjit Diol <rsdiol@mail.com>'
osbf3 whitelist add from 'Olson, Shan (PBMS-SOlson) <solson@pacbell.mobile.com>'
osbf3 whitelist add from 'michael rosenblatt <mr4@andrew.cmu.edu>'
osbf3 whitelist add from 'Nick Taylor <ntaylor@iname.com>'
osbf3 whitelist add from '"Ameen Suleman" <suleman@mhv.net>'
osbf3 whitelist add from 'Dan Overholt <dano@media.mit.edu>'
osbf3 whitelist add from 'Oliver Roup <oroup@media.mit.edu>'
osbf3 whitelist add from 'Bakhtiar Mikhak <mikhak@media.mit.edu>'
osbf3 whitelist add from '"Bob Kelly" <rkelly@firstunion-reit.com>'
osbf3 whitelist add from 'Mitchel Resnick <mres@media.mit.edu>'
osbf3 whitelist add from 'Ryan Meuth <rmeuth@mail.win.org>'
osbf3 whitelist add from 'PETER EACMEN <babylongod@usa.net>'
osbf3 whitelist add from 'Keith <lectro@acadiacom.net>'
osbf3 whitelist add from 'Jon Ryan Schuck <maddison@iquest.net>'
osbf3 whitelist add from 'Arthur Tretyak <atr188@merle.acns.nwu.edu>'
osbf3 whitelist add from 'Robert Pitts <rip@cs.bu.edu>'
osbf3 whitelist add from '"J.W. Pennington" <jwp@awod.com>'
osbf3 whitelist add from 'Max Davies <mdavies@CAM.ORG>'
osbf3 whitelist add from 'Chen Yung Hsu <hsu3@cooper.edu>'
osbf3 whitelist add from 'Laszlo Roska <lroska@cyberus.ca>'
osbf3 whitelist add from '"Regan Russell" <rrussell@c2.telstra-mm.net.au>'
osbf3 whitelist add from 'Mark Tan <hcoe@hotmail.com>'
osbf3 whitelist add from '"Carlos Fernandez" <softech@ptdprolog.net>'
osbf3 whitelist add from 'Daniel Kornhauser (Comp) <daniel@laguna.fmedic.unam.mx>'
osbf3 whitelist add from '"Guy M. Snodgrass" <navyguy@ai.mit.edu>'
osbf3 whitelist add from '"Stefano Falconetti" <falconetti@sigma.it>'
osbf3 whitelist add from 'Pierre Deprost <Pierre.Deprost@Advalvas.be>'
osbf3 whitelist add from 'Thomas Heidel <theidel@advis.de>'
osbf3 whitelist add from 'Tamara Lackner <tlackner@media.mit.edu>'
osbf3 whitelist add from 'Alf Hendrik Kuchenbuch <alf.kuchenbuch@ofw.pr.siemens.de>'
osbf3 whitelist add from 'edmund <ho106@singnet.com.sg>'
osbf3 whitelist add from 'Ken Hornstein <kenh@cmf.nrl.navy.mil>'
osbf3 whitelist add from 'Mitchel Resnick <mres@media.mit.edu> (by way of Mitchel Resnick <mres@media.mit.edu>)'
osbf3 whitelist add from 'ethan getz <ethang@unm.edu>'
osbf3 whitelist add from '"Junby Samonte" <09414797@mail4.dlsu.edu.ph>'
osbf3 whitelist add from 'MSMKatz <msmkatz@wxs.nl>'
osbf3 whitelist add from '"Michael F. Vineyard" <mvineyar@richmond.edu>'
osbf3 whitelist add from 'Chuck McManis <cmcmanis@mcmanis.com>'
osbf3 whitelist add from 'Gary Livick <glivick@pacbell.net>'
osbf3 whitelist add from 'Yonatan Mittlefehldt <yonatan@andrew.cmu.edu>'
osbf3 whitelist add from 'Ian Nieves <wired@cmu.edu>'
osbf3 whitelist add from 'Kam Leang <kleang@eng.utah.edu>'
osbf3 whitelist add from 'Duncan Orthner <orthner@idirect.com>'
osbf3 whitelist add from 'His Dudeness <eyoung@carbon.cudenver.edu>'
osbf3 whitelist add from 'Joey Sims <Joey.Sims@PonyComputer.com>'
osbf3 whitelist add from 'Andrey Korytov <korytov@phys.ufl.edu>'
osbf3 whitelist add from 'Mike Ford <mike.ford@mrc-cbu.cam.ac.uk>'
osbf3 whitelist add from 'Isaac Elishakoff <ielishak@me.fau.edu>'
osbf3 whitelist add from 'vladik <vladik@cs.utep.edu>'
osbf3 whitelist add from '"Eat Bugs!" <jwp@awod.com>'
osbf3 whitelist add from 'Nick Taylor <ntaylor@jps.net>'
osbf3 whitelist add from '"Joe Marie J. Maja" <maja@robotics.is.tohoku.ac.jp>'
osbf3 whitelist add from 'Eduardo Gonzalez <eduardgo@df1.telmex.net.mx>'
osbf3 whitelist add from 'Fred G Martin <fredm@media.mit.edu>'
osbf3 whitelist add from '"Barry A. Muise" <toadbam@bu.edu>'
osbf3 whitelist add from '"Mark E. McNeil" <blades99@eznet.net>'
osbf3 whitelist add from 'Christopher Hart <hart@caltech.edu>'
osbf3 whitelist add from 'Jean-Christophe <tempestj@boole.imag.fr>'
osbf3 whitelist add from 'Chul-hun Han <chhan@hanjung.co.kr>'
osbf3 whitelist add from 'David Holsclaw <davidh@dra.com>'
osbf3 whitelist add from 'Kenneth Forster <kforster@u.arizona.edu>'
osbf3 whitelist add from '"Matt Austin" <Falinn@ukltd90.freeserve.co.uk>'
osbf3 whitelist add from 'John Vaughn <vaughn@HWS.EDU>'
osbf3 whitelist add from '"Jonathan C. Forster" <jforster@psy1.psych.arizona.edu>'
osbf3 whitelist add from 'raj k <robo_helpmate@yahoo.com>'
osbf3 whitelist add from '"Matt Austin" <Falinn@ukmax.com>'
osbf3 whitelist add from '"JensGraf" <JensGraf@gmx.de>'
osbf3 whitelist add from 'Duong Henry <henryd15@yahoo.com>'
osbf3 whitelist add from 'phil white <losttrooper@hotmail.com>'
osbf3 whitelist add from 'Sean Verret <verret@ee.ualberta.ca>'
osbf3 whitelist add from 'Lionel Tay <lioneltay@email.com>'
osbf3 whitelist add from '"j.c.f." <jforster@psy1.psych.arizona.edu>'
osbf3 whitelist add from '"Victor Lee" <leetbvic@singnet.com.sg>'
osbf3 whitelist add from 'Martin Frischherz <frisch@kapsch.net>'
osbf3 whitelist add from '"Landahl, Bill" <Bill.Landahl@morganite.com>'
osbf3 whitelist add from '"Alex Stewart" <robotman5@hotmail.com>'
osbf3 whitelist add from '"Russell, Casey" <crussell@osec.com>'
osbf3 whitelist add from 'Zenon Kulpa <zkulpa@zmit1.ippt.gov.pl>'
osbf3 whitelist add from 'Steve Morris <smorris@nexen.com>'
osbf3 whitelist add from 'Fred Reyes <reyesfred@xoommail.com>'
osbf3 whitelist add from 'Joshua Stein <jstein@es.ucsc.edu>'
osbf3 whitelist add from '"Lola Llamazales" <alola@worldnet.att.net>'
osbf3 whitelist add from 'Said Berriah <berriah@gel.usherb.ca>'
osbf3 whitelist add from 'Kathleen M Pohlman <pohlman@cse.buffalo.edu>'
osbf3 whitelist add from '"Russ Cox" <rsc@plan9.bell-labs.com>'
osbf3 whitelist add from 'Chris Przirembel <rutgers@ces.clemson.edu>'
osbf3 whitelist add from 'Loretta A Willis <loretta@cs.virginia.edu>'
osbf3 whitelist add from 'Lucy Freed <freed@csee.wvu.edu>'
osbf3 whitelist add from 'ECE Graduate Program <ece-grad-program@ces.clemson.edu>'
osbf3 whitelist add from 'Angi Smith <ajsmith@bobcat.ent.ohiou.edu>'
osbf3 whitelist add from 'Admissions <Admissions@admin.fsu.edu>'
osbf3 whitelist add from '"Jens Graf" <JensGraf@gmx.de>'
osbf3 whitelist add from 'redruth <stevet@camtech.net.au>'
osbf3 whitelist add from '"Matthew Finkbeiner" <msf@u.arizona.edu>'
osbf3 whitelist add from '"Conboy" <webmaster@ferretnet.org>'
osbf3 whitelist add from '"Mar, Ericson" <ericson.mar@csfb.com>'
osbf3 whitelist add from 'Sean Verret <sean_verret@pmc-sierra.bc.ca>'
osbf3 whitelist add from 'Michael N Rosenblatt <mr4@andrew.cmu.edu>'
osbf3 whitelist add from 'Edward Delaney <edwardd@earlham.edu>'
osbf3 whitelist add from '"Mulampaka, Kalyan (GEIS, ASI)" <Kalyan.Mulampaka@geis.ge.com>'
osbf3 whitelist add from '"Paul Dito" <pcd@dolby.com>'
osbf3 whitelist add from '"John P. Kline" <kline@darwin.psy.fsu.edu>'
osbf3 whitelist add from '"C. Fort" <cfort@U.Arizona.EDU>'
osbf3 whitelist add from 'Chen-Yung Hsu <cyhsu@afb.net>'
osbf3 whitelist add from 'Michael Miranda <mikmiranda@yahoo.com>'
osbf3 whitelist add from '"pgasparik" <pgasparik@yahoo.com>'
osbf3 whitelist add from '"Andrew Walker" <andal_@hotmail.com>'
osbf3 whitelist add from '"spidersoft (Sam Portillo)" <SPortillo@spidersoft.org>'
osbf3 whitelist add from '"William Ho" <ukho@tm.net.my>'
osbf3 whitelist add from '"Florent Gilles" <f.gillesNOSPAM@xpedite.fr>'
osbf3 whitelist add from 'Jeff Newton <newton@efn.org>'
osbf3 whitelist add from 'Greg Starr <starr@unm.edu>'
osbf3 whitelist add from '"clay." <discord@MIT.EDU>'
osbf3 whitelist add from '"Susanna Lau" <su.lau@uws.edu.au>'
osbf3 whitelist add from '"Clancy Nelson" <nelson3@jcn1.com>'
osbf3 whitelist add from 'John Bachman <bachman@anatek.mv.com>'
osbf3 whitelist add from '"glashan" <lynneg@mweb.co.za>'
osbf3 whitelist add from 'Dovi Poznanski <dovip@post.tau.ac.il>'
osbf3 whitelist add from 'James Munro <jimmn@xnet.com>'
osbf3 whitelist add from 'Michael Johnston <m.johnston@latrobe.edu.au>'
osbf3 whitelist add from '"Jeroen van der Vegt" <A.J.vanderVegt@ITS.TUDelft.nl>'
osbf3 whitelist add from '"Ensio Tammi" <ensio.tammi@realitymodeler.com>'
osbf3 whitelist add from 'Matt Davis <matt.davis@mrc-cbu.cam.ac.uk>'
osbf3 whitelist add from 'Matthew Chung <b437702@mailserv.cuhk.edu.hk>'
osbf3 whitelist add from 'Kam K Leang <kleang@eng.utah.edu>'
osbf3 whitelist add from 'rmtmd <rmtmd@concentric.net>'
osbf3 whitelist add from 'Jerry Packard <j-packard@uiuc.edu>'
osbf3 whitelist add from 'Fabian Lopez <fabian@einstein.tvi.cc.nm.us>'
osbf3 whitelist add from 'Boris New <Boris.New@psycho.univ-paris5.fr>'
osbf3 whitelist add from 'Giang Tran <gt4025@chi.devry.edu>'
osbf3 whitelist add from 'Igor Diko <igord@softhome.net>'
osbf3 whitelist add from '"Kah Mun" <lowk@union.edu>'
osbf3 whitelist add from '"Way Lam" <way@polyu.hknet.com>'
osbf3 whitelist add from '"George Musser Jr" <gmusser@hotmail.com>'
osbf3 whitelist add from '"David Perry" <davidperry@geocities.com>'
osbf3 whitelist add from '"Dennis Clark" <dlc@verinet.com>'
osbf3 whitelist add from '"Ray Tang" <raytang_1@hotmail.com>'
osbf3 whitelist add from 'Mike Schubert <schubi@interface-business.de>'
osbf3 whitelist add from 'William Bain <montanawill@yahoo.com>'
osbf3 whitelist add from '"E158 (M.FAZAL)" <M.FAZAL@bham-eee-fs4.bham.ac.uk>'
osbf3 whitelist add from '"Sunil Kumar" <sunil@uci.edu>'
osbf3 whitelist add from 'Dirk Janssen <dirkj@u.arizona.edu>'
osbf3 whitelist add from 'Eric Shamay <eshamay@polymail.cpunix.calpoly.edu>'
osbf3 whitelist add from 'Will Bain <willb@selway.umt.edu>'
osbf3 whitelist add from '"Scott Harris" <scottrharris@earthlink.net>'
osbf3 whitelist add from 'nat amvat <natamvat@yahoo.com>'
osbf3 whitelist add from 'Christopher Prosser <cprosser@acm.org>'
osbf3 whitelist add from 'Lucio De Re <lucio@proxima.alt.za>'
osbf3 whitelist add from '"Derek Healy" <helix7_99@yahoo.com>'
osbf3 whitelist add from 'root <root@localhost.localdomain>'
osbf3 whitelist add from '"David Young" <djyoung@voyager.co.nz>'
osbf3 whitelist add from 'Ish Rattan <ishwar@pali.cps.cmich.edu>'
osbf3 whitelist add from 'Vladimir Prokopic <prokopic@yahoo.com>'
osbf3 whitelist add from 'KIM LEE JUNG <kim6@cooper.edu>'
osbf3 whitelist add from 'Bill Bynum <bynum@CS.WM.EDU>'
osbf3 whitelist add from '"Pamela Johnson" <pamela.johnson@resumecard.com>'
osbf3 whitelist add from 'fazzini <fazzini@cnea.gov.ar>'
osbf3 whitelist add from '"Fernando Torres" <ftorres@david.ucsc.cl>'
osbf3 whitelist add from '"ê°Óñ·å" <zangyf@263.net>'
osbf3 whitelist add from 'Todd Ahlstrom <todda@xmission.com>'
osbf3 whitelist add from '"Bob Hanson" <Opasan43@hotmail.com>'
osbf3 whitelist add from '"T. Gathright" <terrygathright@home.com>'
osbf3 whitelist add from '"Roger Hamlett" <roger@ttelmah.demon.co.uk>'
osbf3 whitelist add from '"Jose Luis" <jldf@mail.com>'
osbf3 whitelist add from 'Mario Fific <mfific@indiana.edu>'
osbf3 whitelist add from 'racic luka <rackom@panet.bits.net>'
osbf3 whitelist add from '"Steve Stevens" <stevensl@spawar.navy.mil>'
osbf3 whitelist add from 'John Hatton <john.hatton@uk.airsysatm.thomson-csf.com>'
osbf3 whitelist add from '"Patrick Hui" <huip@hkstar.com>'
osbf3 whitelist add from 'Jack Barnett <jbarnett@ixc.net>'
osbf3 whitelist add from 'Jerry Normandin <jerrynormandin@ne.mediaone.net>'
osbf3 whitelist add from 'Jason Parks <jtparks@flashcom.net>'
osbf3 whitelist add from 'Alexander Viro <viro@math.psu.edu>'
osbf3 whitelist add from '"John G. Anderson" <jga@seismo.unr.edu>'
osbf3 whitelist add from '"Pamela Perschler" <pamelap@email.arizona.edu>'
osbf3 whitelist add from '"Fred G. Martin" <fredm@alum.mit.edu>'
osbf3 whitelist add from 'Lee Ryan <ryant@u.arizona.edu>'
osbf3 whitelist add from '"J. Dosher" <jdosher@u.washington.edu>'
osbf3 whitelist add from '"Nabil Saba" <nsaba@ric.ric.uci.edu>'
osbf3 whitelist add from 'Greg Hayward <ghayward@ix.netcom.com>'
osbf3 whitelist add from 'John McChesney-Young <panis@PACBELL.NET>'
osbf3 whitelist add from 'Jennifer Johnson <johnsjen@email.arizona.edu>'
osbf3 whitelist add from '"Francisco Chinchilla" <fchinchi@richmond.edu>'
osbf3 whitelist add from 'John Louie <louie@seismo.unr.edu>'
osbf3 whitelist add from 'Danielle Delgado <ddelgado@mit.edu>'
osbf3 whitelist add from 'Petr Swedock <petr@ai.mit.edu>'
osbf3 whitelist add from 'Patti Fitzpatrick <pfitzpat@mit.edu>'
osbf3 whitelist add from '"Gill A.. Pratt" <gill@legserve.ai.mit.edu>'
osbf3 whitelist add from 'CERT Advisory <cert-advisory@cert.org>'
osbf3 whitelist add from 'Mike Strauss <strauss@mail.nhn.ou.edu>'
osbf3 whitelist add from 'Chip Coldwell <coldwell@frank.harvard.edu>'
osbf3 whitelist add from '"Liisa Simon" <lsimon@ccny.cuny.edu>'
osbf3 whitelist add from '"Robert Baroz" <Robert_Baroz@breadnet.middlebury.edu>'
osbf3 whitelist add from '"Phil McLewin" <phil@mclewin.com>'
osbf3 whitelist add from '"Green, Terri L." <tgreen@nsf.gov>'
osbf3 whitelist add from '"HEATHER STRANDELL" <HSTRANDELL@altru.org>'
osbf3 whitelist add from '"Paul Williams" <prw@bw.beachwood.k12.oh.us>'
osbf3 whitelist add from 'Daehyun Kim <daehyun@csl.cornell.edu>'
osbf3 whitelist add from 'Walter Bell <wbell@CS.Cornell.EDU>'
osbf3 whitelist add from 'Prince Samar <samar@ece.cornell.edu>'
osbf3 whitelist add from '"Venu Ramasubramanian" <ramasv@CS.Cornell.EDU>'
osbf3 whitelist add from 'Charles Szpara <cszpara@acsu.buffalo.edu>'
osbf3 whitelist add from 'Jeffery Dunbar <dunbarj@uballiance.buffalo.edu>'
osbf3 whitelist add from 'Carla Meskill <CMeskill@uamail.albany.edu>'
osbf3 whitelist add from '"Virantha N. Ekanayake" <viran@csl.cornell.edu>'
osbf3 whitelist add from '"Avneesh Bhatnagar" <avneesh@csl.cornell.edu>'
osbf3 whitelist add from 'Indranil Gupta <gupta@CS.Cornell.EDU>'
osbf3 whitelist add from '"Walter Schmidt" <was@VR-Web.de>'
osbf3 whitelist add from 'Robert Crockett <mookie@astro.berkeley.edu>'
osbf3 whitelist add from 'carl heiles <heiles@astro.berkeley.edu>'
osbf3 whitelist add from 'Shauna Sallmen <sallmen@ssl.berkeley.edu>'
osbf3 whitelist add from 'Rowland McDonnell <rowland.mcdonnell@physics.org>'
osbf3 whitelist add from 'Thierry Bouche <thierry.bouche@ujf-grenoble.fr>'
osbf3 whitelist add from '"James H. Cloos Jr." <cloos@jhcloos.com>'
osbf3 whitelist add from '"MicroPress Inc." <support@micropress-inc.com>'
osbf3 whitelist add from 'Ruben Carbonell <goHCI@cmu.edu>'
osbf3 whitelist add from '&quot;Farmer, Rainier&quot; &lt;<A HREF="mailto:Rainier.Farmer@orst.edu">Rainier.Farmer@orst.edu</A>&gt;'
osbf3 whitelist add from 'Richard, Mack L [mailto:<A HREF="mailto:mrichar@iupui.edu">mrichar@iupui.edu</A>]'
osbf3 whitelist add from 'Sebastian Rahtz <sebastian.rahtz@computing-services.oxford.ac.uk>'
osbf3 whitelist add from 'Joseph Lorenzo Hall <jhall@astro.berkeley.edu>'
osbf3 whitelist add from '"Michael Wilson" <path2wealth2002@yahoo.com>'
osbf3 whitelist add from '"Caruso, Holly" <hcaruso@richmond.edu>'
osbf3 whitelist add from '"Berthold K.P. Horn" <bkph@ai.mit.edu>'
osbf3 whitelist add from '"Xin Zhang" <xz56@cornell.edu>'
osbf3 whitelist add from 'Sean Welch <smw17@cornell.edu>'
osbf3 whitelist add from 'gilfoyle <ggilfoyl@mindspring.com>'
osbf3 whitelist add from 'Thomas Roeder <tmroeder@CS.Cornell.EDU>'
osbf3 whitelist add from '"St. Laurent, Tim" <tstlaure@richmond.edu>'
osbf3 whitelist add from '"Peter \(Sci\)" <scifox@asylum30.freeserve.co.uk>'
osbf3 whitelist add from '"Stefanovski, Sasko" <sstefano@richmond.edu>'
osbf3 whitelist add from '"Magpie" <magpie1@frontiernet.net>'
osbf3 whitelist add from '"L. Parker" <lparker@cacaphony.net>'
osbf3 whitelist add from 'Bob Greenberg &lt;<A HREF="mailto:robert.greenberg@nist.gov">robert.greenberg@nist.gov</A>&gt;'
osbf3 whitelist add from 'steven james <pyro@linuxlabs.com>'
osbf3 whitelist add from 'Adam Kravetz <adam@graphics.cornell.edu>'
osbf3 whitelist add from 'Jay Hennigan <jay@west.net>'
osbf3 whitelist add from 'Luminita Todor <luminita@jlab.org>'
osbf3 whitelist add from '"Michael F. Vineyard" <vineyarm@union.edu>'
osbf3 whitelist add from '"Souleret, George" <gsoulere@richmond.edu>'
osbf3 whitelist add from '"Kenneth Forster" <kforster@u.arizona.edu>'
osbf3 whitelist add from '"Rua Haszard Morris" <r.haszard@uws.edu.au>'
osbf3 whitelist add from 'Derek Eder <derek.eder@neuro.gu.se>'
osbf3 whitelist add from 'Feng Wang <wangf@cs.utexas.edu>'
osbf3 whitelist add from '"wanggm" <wanggm107@nenu.edu.cn>'
osbf3 whitelist add from 'Paula Tavares <paula.tavares@mrc-cbu.cam.ac.uk>'
osbf3 whitelist add from '"Tom Frahm" <tfrahm@atipa.com>'
osbf3 whitelist add from '"=?EUC-KR?B?uc69wrHi?=" <eyepo@hanmail.net>'
osbf3 whitelist add from '"Vanessa Shokeir" <vshokeir@hotmail.com>'
osbf3 whitelist add from 'James Colby Kraybill <colby@astro.berkeley.edu>'
osbf3 whitelist add from 'Zodiac Webster <zwebster@csusb.edu>'
osbf3 whitelist add from '"Glenn Morton" <glennmorton@entouch.net>'
osbf3 whitelist add from 'Katia Duscherer <kduscher@ulb.ac.be>'
osbf3 whitelist add from 'Kevin Schmidt <kps@ucsb.edu>'
osbf3 whitelist add from 'Vijay Kumar                                                                                                                      <vk66@cornell.edu>'
osbf3 whitelist add from 'Norm Matloff <matloff@laura.cs.ucdavis.edu>'
osbf3 whitelist add from 'E. Todd Atkins <Todd.Atkins@ucsb.edu>'
osbf3 whitelist add from '"Alex" <alexfaerosa@uol.com.br>'
osbf3 whitelist add from '"Andy" <woodsat@tcd.ie>'
osbf3 whitelist add from '"Zhuang Jie" <zhuangj@hkusua.hku.hk>'
osbf3 whitelist add from '"Matthew Finkbeiner" <msf@wjh.harvard.edu>'
osbf3 whitelist add from 'Andrea McCarthy <Andrea01@AcademicKeys.com>'
osbf3 whitelist add from '"Irina a. Sekerina" <sekerina@postbox.csi.cuny.edu>'
osbf3 whitelist add from '=?gb2312?q?xiang=20wang?= <wang0916xia@yahoo.com.cn>'
osbf3 whitelist add from 'abdessatar mahfoudhi <mabessatar@yahoo.com>'
osbf3 whitelist add from '"laurie cestnick" <laur@canoemail.com>'
osbf3 whitelist add from 'Stuart Bell <s.bell@psychol.cam.ac.uk>'
osbf3 whitelist add from '=?iso-8859-1?q?KEVIN=20GLOVER?= <kevin.glover@btinternet.com>'
osbf3 whitelist add from '"Nicholas J.S. Gibson" <njsjg2@hermes.cam.ac.uk>'
osbf3 whitelist add from 'Maarten van Casteren <Maarten.van-Casteren@mrc-cbu.cam.ac.uk>'
osbf3 whitelist add from '"Jay Bohland" <jbohland@cns.bu.edu>'
osbf3 whitelist add from 'Martine Ceberio <martineceberio@yahoo.com>'
osbf3 whitelist add from '"Virginia M. Holmes" <v.holmes@psych.unimelb.edu.au>'
osbf3 whitelist add from '"Slava Nesterov" <slnest@mail.ru>'
osbf3 whitelist add from '"Ray Moore" <rmoore17@columbus.rr.com>'
osbf3 whitelist add from 'Vladik Kreinovich <vladik@cs.utep.edu>'
osbf3 whitelist add from '"Walker, Darren" <DWalker@uwic.ac.uk>'
osbf3 whitelist add from '"Martin Berz" <berz@msu.edu>'
osbf3 whitelist add from 'C A Ankerstein <hcp02caa@sheffield.ac.uk>'
osbf3 whitelist add from '"Íõ¹úÃ÷" <wanggm107@nenu.edu.cn>'
osbf3 whitelist add from '"R. Baker Kearfott" <rbk@louisiana.edu>'
osbf3 whitelist add from 'Gerlinda Roland <groland@GBHEM.ORG>'
osbf3 whitelist add from '"Jiawang Nie" <njw@Math.Berkeley.EDU>'
osbf3 whitelist add from '"Quarterly Journal" <qjpam@henu.edu.cn>'
osbf3 whitelist add from '"Christophe Jermann" <christophe.jermann@univ-nantes.fr>'
osbf3 whitelist add from 'Daita Domnica Ciobanu <ddc45@columbia.edu>'
osbf3 whitelist add from 'Jeff Tupper <tupper@peda.com>'
osbf3 whitelist add from '"tanya dolis" <tanyadolis@web.de>'
osbf3 whitelist add from 'Michael Trigoboff <mltsoftware@comcast.net>'
osbf3 whitelist add from 'Matt McGann <mcgann@MIT.EDU>'
osbf3 whitelist add from '"Siegfried M. Rump" <rump@tu-harburg.de>'
osbf3 whitelist add from 'Michael Wenger <mjw19@psu.edu>'
osbf3 whitelist add from 'Joanna Tong <jotong@MIT.EDU>'
osbf3 whitelist add from 'Peter Hertling <hertling@informatik.unibw-muenchen.de>'
osbf3 whitelist add from 'Marti F Bolivar <mbolivar@MIT.EDU>'
osbf3 whitelist add from 'Jacquie Snow <snow@unimelb.edu.au>'
osbf3 whitelist add from 'Scott Johnston <johnston@MIT.EDU>'
osbf3 whitelist add from 'Eric Firing <efiring@hawaii.edu>'
osbf3 whitelist add from 'Harvey Jones <harveyj@gmail.com>'
osbf3 whitelist add from 'Emily M Levesque <emsque@MIT.EDU>'
osbf3 whitelist add from 'Rob Radez <rradez@MIT.EDU>'
osbf3 whitelist add from 'Nicholas Riches <nickgriches@yahoo.co.uk>'
osbf3 whitelist add from 'Ilias Kotsireas <ikotsire@wlu.ca>'
osbf3 whitelist add from 'George Corliss <George.Corliss@marquette.edu>'
osbf3 whitelist add from 'Alain Moussiaux <Alain.Moussiaux@fundp.ac.be>'
osbf3 whitelist add from 'Alberto Yorio <albertoyorio@yahoo.com>'
osbf3 whitelist add from 'Juhree Patterson <jpatters@yccd.edu>'
osbf3 whitelist add from 'Shane Lindsay <shanejunk@gmail.com>'
osbf3 whitelist add from 'Markus Neher <markus.neher@math.uni-karlsruhe.de>'
osbf3 whitelist add from 'Eduardo Gomez-Ramirez <egr@ci.ulsa.mx>'
osbf3 whitelist add from 'Ekaterina Kostina <Ekaterina.Kostina@iwr.uni-heidelberg.de>'
osbf3 whitelist add from 'Jerzy Wasniewski <jw@imm.dtu.dk>'
osbf3 whitelist add from 'giuseppe <demarco@fit.ac.jp>'
osbf3 whitelist add from '"PaLC Inc" <president@palc.org>'
osbf3 whitelist add from 'Holly Robertson <hollyr@ischool.utexas.edu>'
osbf3 whitelist add from 'Laura Cosovanu <laura007@gmail.com>'
osbf3 whitelist add from 'Markus Grimmer <grimmer@math.uni-wuppertal.de>'
osbf3 whitelist add from 'Emily Hebard <ewheb@yahoo.com>'
osbf3 whitelist add from '"Luke Achenie" <achenie@engr.uconn.edu>'
osbf3 whitelist add from 'Mrudula Yadav <mrudul_yadav@yahoo.com>'
osbf3 whitelist add from 'JOHN J CURTIN <jjcurtin@facstaff.wisc.edu>'
osbf3 whitelist add from 'Skidmore Spam Firewall <spam-alerts@skidmore.edu>'
osbf3 whitelist add from '"Andrzej Pownuk" <Andrzej.Pownuk@polsl.pl>'
osbf3 whitelist add from 'Yuval Marton <yuvalmarton@gmail.com>'
osbf3 whitelist add from 'John Curtin <jjcurtin@wisc.edu>'
osbf3 whitelist add from '"Virginia Kay" <vek2001@columbia.edu>'
osbf3 whitelist add from '"Mark Conroy" <Mark.Conroy@unisa.edu.au>'
osbf3 whitelist add from 'Lauren Lukkarila <llukkarila@yahoo.com>'
osbf3 whitelist add from '"Kreinovich, Vladik" <vladik@utep.edu>'
osbf3 whitelist add from '"Heather E. McInnis" <hmcinnis@uoregon.edu>'
osbf3 whitelist add from '"PlayerGuest" <sjp@uoregon.edu>'
osbf3 whitelist add from 'Mark Gebhart <mgebhart@cs.utexas.edu>'
osbf3 whitelist add from 'V Nguyen <V.Nguyen@sheffield.ac.uk>'
osbf3 whitelist add from '"Rafi Muhanna" <rafi.muhanna@gtrep.gatech.edu>'
osbf3 whitelist add from '"Kevin Resnick" <KResnick@sortinc.com>'
osbf3 whitelist add from 'Tracy Gerstle <tgerstle@yahoo.com>'
osbf3 whitelist add from '"Kartik K. Agaram" <akkartik@cs.utexas.edu>'
osbf3 whitelist add from 'Steve Keckler <skeckler@cs.utexas.edu>'
osbf3 whitelist add from 'Hui Yui Chi <huiyuichi@gmail.com>'
osbf3 whitelist add from 'ARL Communications <commlmgr@arl.org>'
osbf3 whitelist add from 'US-CERT Security Bulletins <security-bulletins@us-cert.gov>'
osbf3 whitelist add from '"Normand Arsenault" <normand.arsenault@sympatico.ca>'
osbf3 whitelist add from '"Vannessa Wong" <lpyxvcmw@nottingham.ac.uk>'
osbf3 whitelist add from 'Mark Benthien <benthien@usc.edu>'
osbf3 whitelist add from 'US-CERT Alerts <alerts@us-cert.gov>'
osbf3 whitelist add from '"Bassett, Matthew" <mhbassett@dow.com>'
osbf3 whitelist add from 'US-CERT Technical Alerts <technical-alerts@us-cert.gov>'
osbf3 whitelist add from 'Peter Straffon <p.straffon@psych.unimelb.edu.au>'
osbf3 whitelist add from '"Chris Letts" <Chris.Letts@newcastle.ac.uk>'
osbf3 whitelist add from 'Yvonne Aburrow <Y.Aburrow@bath.ac.uk>'
osbf3 whitelist add from '"R. Baker" <rb373@cam.ac.uk>'
osbf3 whitelist add from 'Joao Verissimo <jl.verissimo@gmail.com>'
osbf3 whitelist add from 'Brett Reid <brett.reid@utas.edu.au>'
osbf3 whitelist add from '"Shiaohui Chan" <shiaohui@u.arizona.edu>'
osbf3 whitelist add from '"Nebe-Von-Caron, G" <g.nebe-von-caron@unipath.com>'
osbf3 whitelist add from '"D. G. Meyer" <meyer@purdue.edu>'
osbf3 whitelist add from '"Skidmore Spam Firewall" <spam-reports@skidmore.edu>'
osbf3 whitelist add from 'Oliver Kennedy <okennedy@cs.cornell.edu>'
osbf3 whitelist add from '"Kelvin So" <kelvinso@cs.cornell.edu>'
osbf3 whitelist add from '"Ian Kash" <kash@cs.cornell.edu>'
osbf3 whitelist add from 'Stevan Harnad <harnad@ecs.soton.ac.uk>'
osbf3 whitelist add from 'Jason Hale <jghale@olemiss.edu>'
osbf3 whitelist add from 'Huang Shiang-Jia <sh366@cornell.edu>'
osbf3 whitelist add from 'Derek Eder <derek_eder@yahoo.com>'
osbf3 whitelist add from 'Ivan Stoyanov <ids3@cornell.edu>'
osbf3 whitelist add from '"Abhishek Santosh Gupta" <asg46@cornell.edu>'
osbf3 whitelist add from 'Jeff Diamond <jdiamond@cs.utexas.edu>'
osbf3 whitelist add from '"Kevin" <km266@cornell.edu>'
osbf3 whitelist add from '"Ryan S. Peterson" <ryanp@cs.cornell.edu>'
osbf3 whitelist add from 'Virginia Holmes <vmholmes@unimelb.edu.au>'
osbf3 whitelist add from '"Andrew Cunningham" <lackhand@gmail.com>'
osbf3 whitelist add from '"La'"'"'Shonn Curry" <lccurry2@hotmail.com>'
osbf3 whitelist add from 'Dana Samson <d.samson@bham.ac.uk>'
osbf3 whitelist add from '"Shane Lindsay" <shanejunk@gmail.com>'
osbf3 whitelist add from 'Philip Kuryloski <pjk25@cornell.edu>'
osbf3 whitelist add from '"Nicholas S Gerner" <nsg7@cornell.edu>'
osbf3 whitelist add from '"George Porter" <george@library.caltech.edu>'
osbf3 whitelist add from 'Amy Mioduszewski <amiodusz@nrao.edu>'
osbf3 whitelist add from '"Souhila Messaoud-Galusi" <souhila@phonetics.ucl.ac.uk>'
osbf3 whitelist add from 'DBNet Account <dbnet@ncosrv1.ncep.noaa.gov>'
osbf3 whitelist add from '"Annalisa Setti" <annalisasetti@fastwebnet.it>'
osbf3 whitelist add from '"Bonnie Reid" <breid@housing.olemiss.edu>'
osbf3 whitelist add from 'Niranjan Sivakumar <ns253@cornell.edu>'
osbf3 whitelist add from '"Liam Proven" <lproven@gmail.com>'
osbf3 whitelist add from 'Souhila Messaoud-Galusi <souhila@phonetics.ucl.ac.uk>'
osbf3 whitelist add from '"Simmons, Tami R." <Tami_Simmons@dfci.harvard.edu>'
osbf3 whitelist add from '"Theodore Ming Shiuan Chao" <tc99@cornell.edu>'
osbf3 whitelist add from 'Madhavi Krishnan <madhavi@cs.utexas.edu>'
osbf3 whitelist add from 'Nick Gerner <nsg7@cornell.edu>'
osbf3 whitelist add from '"Onur Polat" <onurpolat@saatkulesi.net>'
osbf3 whitelist add from '"Agenbroad, James (Civ,ARL/CISD)" <jagenbro@arl.army.mil>'
osbf3 whitelist add from 'Derek Eder <derek.eder@lungall.gu.se>'
osbf3 whitelist add from 'GA <gghw1@yahoo.com>'
osbf3 whitelist add from '"Roy Mersland" <mersland@online.no>'
osbf3 whitelist add from '"Manh Hao Quach" <M.Quach@salford.ac.uk>'
osbf3 whitelist add from 'Hongchuan Zhang <hczhang@ucsd.edu>'
osbf3 whitelist add from '"Daita D. Ciobanu" <ddc45@columbia.edu>'
osbf3 whitelist add from 'Peter Suber <peters@earlham.edu> '
osbf3 whitelist add from '"Bret Miller" <bret.miller@wcg.org>'
osbf3 whitelist add from 'SIU Weather Processor <ldm@weather.admin.niu.edu>'
osbf3 whitelist add from 'LDM Weather <ldm@weather.admin.niu.edu>'
