#! /usr/bin/lua

-- simple example to count training and tests in a log left by train-test

local train = 0
local test = 0

local t = {
  label_by_hand = function(t) io.stdout:write(t.file, ' ', t.class, '\n') end
}

setmetatable(t, { __index = function() return function () end end })

local logfile = assert(arg[1], 'Log file not given!')

local log = assert(loadfile(logfile))

log(t)

